export default {
  async contactCoach(ctx, payload) {
    const newReq = {
      userEmail: payload.email,
      message: payload.message,
    };

    const res = fetch(
      `https://find-a-coach-vue-course-app-default-rtdb.europe-west1.firebasedatabase.app/requests/${payload.coachID}.json`,
      {
        method: 'POST',
        body: JSON.stringify(newReq),
      }
    );

    const resData = await res.json();

    if (!res.ok) {
      const error = new Error(resData.message || 'Failed to send request.');
      throw error;
    }

    // We're adding id to this request that is automatically generated by Firebase
    newReq.id = resData.name;
    newReq.coachID = payload.coachID;

    ctx.commit('addRequest', newReq);
  },

  async fetchRequests(ctx) {
    const coachID = ctx.rootGetters.userID;
    const authToken = ctx.rootGetters.token;
    const res = await fetch(
      `https://find-a-coach-vue-course-app-default-rtdb.europe-west1.firebasedatabase.app/requests/${coachID}.json?auth=${authToken}`
    );
    const resData = await res.json();

    if (!res.ok) {
      const error = new Error(resData.message || 'Failed to fetch requests.');
      throw error;
    }

    const reqs = [];

    for (const key in resData) {
      const req = {
        id: key,
        coachID,
        userEmail: resData[key].userEmail,
        message: resData[key].message,
      };

      reqs.push(req);
    }

    ctx.commit('setRequests', reqs);
  },
};
